# Week 6 Project

## Nicola Morrow

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

```{r cache = TRUE}
data_site <- 
  "http://tiny.cc/dcf/2014-Q4-Trips-History-Data-Small.rds" 
Trips <- readRDS(gzcon(url(data_site)))

library(lubridate)
```

### 1 

```{r}
Trips %>%
  ggplot(aes(x=sdate)) + geom_density()
```

### 2

```{r}
Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day)) + geom_density()
```

### 3

```{r}
Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  mutate(day_of_week = lubridate::wday(sdate)) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day)) + geom_density() + facet_wrap(~ day_of_week)
```

### 4 

```{r}
Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  mutate(day_of_week = lubridate::wday(sdate, label=TRUE)) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day, alpha=0.5)) + geom_density(aes(color=client)) + facet_wrap( ~ day_of_week)
```

### 5

```{r}
Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  mutate(day_of_week = lubridate::wday(sdate, label=TRUE)) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day)) + geom_density(position = position_stack()) + facet_wrap(~ day_of_week)
```

I think that 5 is probably the most effective way of presenting the data because it gives all of the different dimensions at once and eliminates the cases that don't have good data.

### 6 

```{r}
Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  mutate(wday = ifelse(lubridate::wday(sdate) %in% c(1,7), "weekend", "weekday")) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day)) + geom_density(aes(color=client)) + facet_wrap(~ wday)

Trips %>%
  mutate(time_of_day = lubridate::hour(sdate) + lubridate::minute(sdate)/60) %>%
  mutate(wday = ifelse(lubridate::wday(sdate) %in% c(1,7), "weekend", "weekday")) %>%
  group_by(time_of_day) %>%
  arrange(desc(time_of_day)) %>%
  ggplot(aes(x=time_of_day)) + geom_density(aes(color=wday)) + facet_wrap(~ client)
```

I think it is better to facet by client and fill by weekday because it tells us which kinds of clients are most likely to shop when.  